# Generated by Django 4.2.1 on 2023-05-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0003_alter_address_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='u_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='c_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='d_id',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='p_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='u_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='c_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='d_id',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='p_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='u_id',
            new_name='user',
        ),
    ]
